version: "3.8"

services:
  app:
    container_name: questo-ssr-dev
    image: questo-ssr-dev
    build:
      context: .
      target: development
    environment:
      - QUESTO_API_URL=${QUESTO_API_URL}
    volumes:
      # sync container changes while developing
      - ./src:/app/src
    ports:
      - 3000:3000
